server:
  http_listen_port: 9080
  log_level: info

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: ros_logs
    static_configs:
      - targets: ['localhost']
        labels:
          job: ros
          __path__: /host_logs/*.log    # <-- CHEMIN à l'intérieur du conteneur (voir docker-compose)
    # pipeline pour parser chaque ligne JSON et extraire des labels
    pipeline_stages:
      - json:
          expressions:
            checkpoint: checkpoint
            zone_type: zone_type
            total_messages_received: total_messages_received
      - labels:
          checkpoint:
          zone_type:
