#version: '3.7'
services:
  loki:
    image: grafana/loki:3.4.1
    container_name: loki
    restart: always
    ports:
      - "3100:3100"
    volumes:
      - ./config/loki-config.yaml:/etc/loki/local-config.yaml:ro
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:3.4.1
    container_name: promtail
    restart: always
    depends_on:
      - loki
    volumes:
      - ./config/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /home/samar/takwa_ws/logs_grafana:/host_logs   # <-- MONTER le dossier rÃ©el d'host
    command: -config.file=/etc/promtail/promtail-config.yaml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456789
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage:
